config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :people
  resources :motors

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
	validates :name, presence: true
	validates :money, presence: true,
										numericality: { greater_than_or_equal_to: 0 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/motors_controller.rb
class MotorsController < ApplicationController
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
	def index
		@people = Person.all
	end

	def show
		@person = Person.find(params[:id])
	end

	def new
		@person = Person.new
	end

	def edit
		@person = Person.find(params[:id])
	end

	def create
		@person = Person.new(person_params)

		if @person.save
			redirect_to @person
		else
			render 'new'
		end
	end

	def update
		@person = Person.find(params[:id])

		if @person.update(person_params)
			redirect_to @person
		else
			render 'edit'
		end
	end

	def destroy
		@person = Person.find(params[:id])
		@person.destroy

		redirect_to people_path
	end

	private
		def person_params
			params.require(:person).permit(:name, :money)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def active_class?(test_path)
    request.path == test_path
  end
end

app/helpers/motors_helper.rb
module MotorsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        
        <%if current_page?(controller: 'people', action: 'index')%>
          <li class="active">
            <a href='javascript:;'>People</a>
          </li>
        <%else%>
          <li>
          <%= link_to('People', people_path) %>
          </li>
        <%end%>
        
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Motor</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>
  	<div class="container">
  		<div class="row">
	  		<%= yield %>
  		</div>
  	</div>
  </body>
  <%= javascript_include_tag 'application' %>
</html>

app/views/people/_form.html.erb
<div class="col-sm-12 text-center"><h3>Person Form</h3></div>

<%= form_for @person, html: {class: 'form-horizontal'} do |f| %>
	<% if @person.errors.any? %>
		<div class="col-sm-2"></div>
    <div class="col-sm-8 alert-danger">
      <h2 class="text-center">
        <%= pluralize(@person.errors.count, "error") %> prohibited
        this person from being saved :
      </h2>
      <ul class="col-sm-offset-1">
        <% @person.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
		<div class="col-sm-2"></div>
  <% end %>

	<div class="form-group col-sm-12">
		<div class="col-sm-3"></div>
		<%= f.label :name, class: 'control-label col-sm-2' %>
		<div class="col-sm-4">
    	<%= f.text_field :name, class: 'form-control' %>
    </div>
		<div class="col-sm-3"></div>
	</div>

	<div class="form-group col-sm-12">
		<div class="col-sm-3"></div>
		<%= f.label :money, class: 'control-label col-sm-2' %>
		<div class="col-sm-4">
    	<%= f.text_field :money, class: 'form-control' %>
    </div>
		<div class="col-sm-3"></div>
	</div>

	<div class="col-sm-12">
		<%= f.submit class: 'btn btn-default center-block' %>
	</div>
<% end %>

app/views/people/edit.html.erb
<%= render 'form' %>

app/views/people/index.html.erb
<table class="table">
	<thead>
		<tr>
			<th>Name</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
		<% @people.each do |person| %>
			<tr>
				<td><%= link_to person.name, person_path(person.id) %></td>
				<td><%= link_to 'Edit', edit_person_path(person.id), class: 'btn btn-primary btn-xs' %> - <%=
								link_to 'Remove', person_path(person.id),
										method: :delete, 
										data: { confirm: "Are you sure to remove #{person.name}?"}, class: 'btn btn-primary btn-xs'%>										
				</td>
			</tr>
		<% end %>
	</tbody>
	<tfoot>
		<tr>
			<td></td>
			<td><ul class="pull-right"><%= link_to 'New', new_person_path, class: 'btn btn-primary btn-xs' %></ul></td>
		</tr>
	</tfoot>
</table>

app/views/people/new.html.erb
<%= render 'form' %>

app/views/people/show.html.erb
<div class="text-center">
	<p>
	  <strong>Name :</strong>
	  <%= @person.name %>
	</p>
	 
	<p>
	  <strong>Money :</strong>
	  <%= @person.money %>
	</p>
</div>